---
include:
  - board: skinner39_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
  - board: skinner39_right
    shield: nice_view
  - board: skinner39_left
    shield: settings_reset
  - board: skinner39_right
    shield: settings_reset
